// ═══════════════════════════════════════════════════════════════════════════
// LANGUAGE MARKERS — Data structures for the 4-phase detection pipeline
// Source: LANGUAGE_DETECTION_FRAMEWORK.md (Moose Tag Scout)
// ═══════════════════════════════════════════════════════════════════════════

// ── 1A: Diagnostic Anchors (DA) — Weight: 4 per match ─────────────────────
// Highest-confidence tokens: copulas, first-person pronouns, unique question words.
export const DIAGNOSTIC_ANCHORS = {
  HI: {
    copula:       ['hai', 'hain', 'he'],
    firstPerson:  ['main', 'mai'],
    questionWord: ['kya', 'kyaa', 'kia'],
  },
  TA: {
    copula:       ['iruku', 'iru', 'illai', 'illa'],
    firstPerson:  ['naan', 'naa'],
    questionWord: ['enna', 'ennaa'],
  },
  TE: {
    copula:       ['undi', 'undu', 'ledu', 'ledhu', 'kaadu', 'kadu'],
    firstPerson:  ['nenu'],
    questionWord: ['emi', 'emee', 'ela', 'elaa'],
  },
  MR: {
    copula:       ['ahe', 'aahe'],
    firstPerson:  ['mi'],
    questionWord: ['kay', 'kaay', 'kuthe', 'kasa', 'kashi'],
  },
  BN: {
    copula:       ['ache', 'aache', 'achho'],
    firstPerson:  ['ami'],
    questionWord: ['kemon', 'kothai', 'kokhon', 'keno'],
  },
  ML: {
    copula:       ['anu', 'aanu'],
    firstPerson:  ['njan', 'njaanu'],
    questionWord: ['enthu', 'entho', 'evide'],
  },
  KN: {
    copula:       ['ide', 'idhe', 'ede'],
    firstPerson:  ['naanu'],
    questionWord: ['enu', 'yenu', 'yelli', 'yaake', 'hege'],
  },
  PA: {
    copula:       ['hanji'],
    firstPerson:  ['assi', 'asin'],
    questionWord: ['kidda', 'kiddan', 'kiddah'],
  },
  GU: {
    copula:       ['chhe', 'che', 'chho', 'chhu'],
    firstPerson:  ['hu', 'hoo'],
    questionWord: ['su', 'shu', 'kem'],
  },
  OD: {
    copula:       [],               // achhi/achi removed — scored only via CS channel with disambiguation
    firstPerson:  ['mun', 'mu'],
    questionWord: ['kana', 'kemiti'],
  },
};

// ── 1B: Exclusive Vocabulary (EV) — Weight: 3 per match ───────────────────
// Tokens that appear in ONLY one language's marker set. No disambiguation needed.
export const EXCLUSIVE_VOCAB = {
  HI: [
    'zyada', 'jyada', 'jada', 'zada',
    'thoda', 'thodi',
    'bilkul',
    'sirf', 'srf', 'sirif',
    'abhi',
    'kyunki', 'kyunke',
    'lekin',
    'sahi', 'shi',
    'galat', 'glat',
    'zabardast',
    'bakwas',
    'wasool',
    'lagta', 'lagti', 'lage',
    'wala', 'waala', 'vala', 'wale',
    'woh', 'wo', 'uska', 'uski',
    'bahut', 'bhot', 'bahot', 'bhut',
  ],
  TA: [
    'romba', 'rombha',
    'poda', 'podaa',
    'seri',
    'ipo', 'ippo',
    'theriyum', 'theriyaadhu',
    'sollu', 'solla',
    'solren', 'solraen',
    'pannrom', 'pannurom',
    'appuram', 'apram',
    'macha',
    'konjam', 'kunjam',
    'kastam', 'kashtam',
    // enna/ennaa removed — already in DA.TA.questionWord
  ],
  TE: [
    'bagundi', 'baagundi',
    'chala', 'chaala',
    'baaga',
    'ante',
    // nenu removed — already in DA.TE.firstPerson
    'andi', 'andee',
    'ekkada',
    'gurinchi',
    'bava', 'bavaa',
    'maama',
    'vastundi',
    'potundi',
    'cheppandi',
    'cheyyi', 'chesaadu',
  ],
  MR: [
    'khup',
    'chaan',
    'mhanje',
    'tyamule',
    'barobar',
    'zalay', 'jhala', 'zala',
    // kuthe, kasa, kashi removed — already in DA.MR.questionWord; kase kept
    'kase',
    'kevha', 'kadhi',
    'gelo', 'gela',
    'sangto',
    'aplya', 'aaplya',
    'tula', 'mala',
    'thambaa', 'thamb',
    'pudhe',
    'yevda', 'yvdha',
  ],
  BN: [
    'bhalo', 'bhaaloh',
    'darun',
    'fatafati', 'fatafaati',
    'pagol', 'paagol',
    'hoyeche', 'hoyche',
    'korchi', 'korchhi',
    'jacchi',
    'ashchi', 'aschhi',
    // kemon, kothai, keno, kokhon removed — already in DA.BN.questionWord; kotha kept
    'kotha',
    'joss',
    'matha kharap',
    'daam beshi',
  ],
  ML: [
    'kollam', 'kollaam',
    'adipoli',
    // njan, njaanu removed — already in DA.ML.firstPerson
    'mone', 'monee',
    'mole', 'moley',
    'chetta', 'cheetta',
    'chechi', 'chechhi',
    'machaan', 'machan',
    'enthoru',
    'pakshe',
    'ingane', 'angane',
    'ariyam', 'ariyum',
    'ariyilla',
    'venam',
    'venda',
    'sheri', 'sheriyanu',
  ],
  KN: [
    'thumba', 'tumba',
    'bombat',
    'chindhi',
    'olle',
    'chennagide',
    'adjusht',
    'bekitha',
    'byawarsi',
    'hushaaru', 'hushar',
    'ivattu',
    'naaley',
    'jaasti',
    'bahala',
    'namma',
    'nodu', 'nodri',
    'haelu',
    'kaelu',
  ],
  PA: [
    'tussi', 'tusi',
    'oye', 'oyee',
    'paji', 'paaji',
    // kidda, kiddan, kiddah removed — already in DA.PA.questionWord
    'vadiya', 'vadia', 'wadia',
    'wich', 'vich',
    'naal', 'nal',
    'putt', 'puttar',
    'sat sri akal', 'waheguru',
    'layi', 'lai',
    // assi, asin removed — already in DA.PA.firstPerson
    'jatt',
    'hunda', 'hundi',
    'lagda', 'lagdi',
  ],
  GU: [
    // chhe/che/chho/chhu removed — already in DA.GU.copula
    // su/shu/kem removed — already in DA.GU.questionWord
    'nathi',
    'kem cho', 'kem chho', 'kem chhe',
    'maza ma', 'majama',
    'aavjo',
    'saru', 'saras', 'saaru',
    'badhu', 'badhun',
    'mitro',
    'thavu', 'thay',
    'male', 'malyu',
  ],
  OD: [
    'pain',
    // mun, mu removed — already in DA.OD.firstPerson
    // kemiti, kana removed — already in DA.OD.questionWord
    'bhala', 'bhalaa',
    'kinichhi',
    'hela', 'hel',
    'jaichi', 'jaichhi',
    'kahibi', 'kahibu',
    'dekhibi',
    'heba', 'hebu',
    'neba', 'nebu',
    'deba', 'debu',
    'ethare', 'ithare',
    'sethare',
    'aaji',
    'sakala',
    'bahuta',
  ],
};

// ── 1C: Morphophonological Patterns (MP) — Weight: 2 per regex match ──────
// Structural suffix and phonological patterns. Regex-based, not word-list lookups.
export const MORPHO_PATTERNS = {
  HI: [
    { pattern: /\b\w*(karna|karta|karti|karo|karte|karke)\b/i, weight: 2 },
    { pattern: /\b\w+(wala|waala|vala|wale)\b/i, weight: 2 },
  ],
  TA: [
    { pattern: /\b\w+kku\b/i, weight: 2 },
    // Negative lookahead excludes English -la words; min 4 chars before -la matches veetla/shopla
    { pattern: /\b(?!formula|vanilla|umbrella|gorilla|villa|capella|manila|camera)[a-z]{4,}la\b/i, weight: 2 },
    { pattern: /\b\w+nga\b/i, weight: 2 },
    { pattern: /\b\w+(ren|raen)\b/i, weight: 2 },
    { pattern: /zh/i, weight: 2 },
    { pattern: /\b\w+u\b/i, weight: 1 },
  ],
  TE: [
    { pattern: /\b\w+undi\b/i, weight: 2 },
    { pattern: /\b\w+andi\b/i, weight: 2 },
    { pattern: /\b\w+ga\b/i, weight: 1 },
    { pattern: /\b\w+lu\b/i, weight: 1 },
  ],
  MR: [
    { pattern: /\b\w+(ahe|aahe)\b/i, weight: 2 },
    { pattern: /\b\w+(cha|chi|che)\b/i, weight: 2 },
    { pattern: /\b(jh|zh)\w+/i, weight: 2 },
  ],
  BN: [
    { pattern: /\b\w+(chhi|cchhi)\b/i, weight: 2 },
    { pattern: /\b\w+(chhe|cchhe)\b/i, weight: 2 },
    // Negative lookahead excludes common English social media words ending in -o
    { pattern: /\b(?!also|solo|hello|video|zero|hero|metro|who|go|do|so|no|pro|ago|too|two|bro|yo|photo|auto|memo|demo|logo|echo|ego|info|intro|bio|geo|radio|audio|studio|ratio)\w{3,}o\b/i, weight: 1 },
  ],
  ML: [
    { pattern: /\bnj\w+/i, weight: 2 },
    // Negative lookahead excludes English -il words; min 4 chars before -il matches veetil/schoolil
    { pattern: /\b(?!detail|retail|pencil|fossil|brazil|april|anvil|email|trail)[a-z]{4,}il\b/i, weight: 2 },
    { pattern: /\b\w+kku\b/i, weight: 1 },
  ],
  KN: [
    { pattern: /\b\w+(alli|illi)\b/i, weight: 2 },
    { pattern: /\b\w+ge\b/i, weight: 2 },
    { pattern: /\baa\b/i, weight: 1 },
  ],
  PA: [
    { pattern: /\b\w+nu\b/i, weight: 1 },
  ],
  GU: [
    { pattern: /\b\w+(nu|ni)\b/i, weight: 1 },
    { pattern: /\b\w+ma\b/i, weight: 1 },
  ],
  OD: [
    { pattern: /\b\w+(ichi|ichhi)\b/i, weight: 2 },
  ],
};

// ── 1D: Disambiguation Map (CS Channel) — Weight: 1 per confirmed match ──
// Tokens shared between languages. Score only if a confirming token is co-present.
export const DISAMBIGUATION_MAP = {
  // ═══ GROUP A: HIGH-FREQUENCY CROSS-LANGUAGE TOKENS ═══
  'nahi': {
    HI: ['hai', 'hain', 'ho', 'kar', 'kya', 'wala', 'waala', 'bahut', 'bhot',
         'zyada', 'jyada', 'yaar', 'bhai', 'lagta', 'lagti', 'lekin', 'sirf'],
    MR: ['ahe', 'aahe', 'ka', 'khup', 'chaan', 'mhanje', 'zalay', 'kuthe',
         'kasa', 'tula', 'mala', 'tyamule', 'barobar'],
    PA: ['hanji', 'paji', 'paaji', 'wich', 'vich', 'oye', 'tussi', 'tusi',
         'vadiya', 'naal', 'kidda', 'kiddan'],
    OD: ['achhi', 'achi', 'pain', 'mun', 'mu', 'bhala', 'kemiti', 'kana',
         'hela', 'kinichhi', 'bahuta'],
  },
  'bhai': {
    HI: ['hai', 'hain', 'bahut', 'bhot', 'kya', 'yaar', 'nahi', 'acha',
         'zyada', 'wala', 'lagta', 'lekin', 'sirf', 'zabardast'],
    PA: ['hanji', 'wich', 'vich', 'oye', 'tussi', 'vadiya', 'naal', 'paji',
         'kidda', 'assi', 'jatt'],
    GU: ['chhe', 'che', 'chho', 'chhu', 'saru', 'kem', 'maza', 'nathi',
         'aavjo', 'badhu', 'su'],
    OD: ['achhi', 'achi', 'bhala', 'mun', 'mu', 'pain', 'hela', 'kemiti',
         'kinichhi', 'bahuta'],
    BN: ['ache', 'aache', 'bhalo', 'ami', 'tumi', 'khub', 'darun',
         'fatafati', 'aar', 'kemon', 'pagol'],
  },
  'da': {
    TA: ['romba', 'rombha', 'illa', 'illai', 'macha', 'nalla', 'enna',
         'konjam', 'kunjam', 'sollu', 'iruku', 'seri', 'appuram', 'poda'],
    TE: ['ante', 'andi', 'andee', 'bagundi', 'baagundi', 'chala', 'chaala',
         'ledu', 'ledhu', 'kaadu', 'undi', 'bava', 'bavaa', 'nenu'],
    BN: ['ache', 'aache', 'bhalo', 'ami', 'tumi', 'khub', 'fatafati',
         'darun', 'aar', 'kemon', 'pagol', 'korchi'],
    PA: ['wich', 'vich', 'tussi', 'tusi', 'oye', 'hanji', 'vadiya',
         'naal', 'paji', 'kidda', 'assi'],
  },
  'na': {
    HI: ['hai', 'hain', 'kar', 'acha', 'achha', 'yaar', 'bhai', 'bahut',
         'nahi', 'kya', 'wala', 'lagta', 'lekin'],
    MR: ['ahe', 'aahe', 'khup', 'chaan', 'ka', 'mhanje', 'zalay', 'kuthe',
         'tula', 'mala', 'aplya', 'tyamule'],
    BN: ['ache', 'aache', 'ami', 'tumi', 'bhalo', 'khub', 'darun',
         'fatafati', 'aar', 'bolo', 'kemon', 'pagol'],
    KN: ['ide', 'idhe', 'ede', 'illa', 'thumba', 'tumba', 'bombat',
         'olle', 'namma', 'beku', 'beda', 'ivattu'],
  },
  'yaar': {
    HI: ['hai', 'hain', 'kya', 'bhai', 'bahut', 'bhot', 'nahi', 'acha',
         'wala', 'zyada', 'lagta', 'lekin'],
    PA: ['hanji', 'wich', 'vich', 'oye', 'tussi', 'vadiya', 'paji',
         'naal', 'kidda', 'assi', 'lagda'],
    TA: ['romba', 'rombha', 'illa', 'illai', 'macha', 'nalla', 'enna',
         'iruku', 'sollu', 'konjam', 'seri', 'appuram'],
  },
  'super': {
    TA: ['da', 'daa', 'illa', 'macha', 'romba', 'nalla', 'enna',
         'iruku', 'konjam', 'sollu', 'seri'],
    TE: ['ga', 'undi', 'undu', 'andi', 'andee', 'ra', 'ante', 'chala',
         'bagundi', 'ledu', 'kaadu', 'bava'],
    KN: ['ide', 'idhe', 'ede', 'illa', 'thumba', 'tumba', 'bombat',
         'olle', 'namma', 'aa', 'beku', 'ivattu'],
  },
  'mast': {
    HI: ['hai', 'hain', 'bahut', 'bhot', 'yaar', 'bhai', 'nahi', 'kya',
         'wala', 'zyada', 'lagta', 'sirf'],
    PA: ['hanji', 'wich', 'vich', 'oye', 'tussi', 'vadiya', 'paji',
         'naal', 'kidda', 'lagda'],
    GU: ['chhe', 'che', 'chho', 'chhu', 'saru', 'maza', 'badhu', 'nathi',
         'kem', 'aavjo', 'su'],
  },
  'bahut': {
    HI: ['hai', 'hain', 'nahi', 'wala', 'kya', 'yaar', 'bhai', 'acha',
         'zyada', 'lagta', 'lekin', 'sirf', 'woh'],
    OD: ['achhi', 'achi', 'pain', 'mun', 'mu', 'bhala', 'kemiti',
         'kana', 'hela', 'kinichhi'],
  },
  'khub': {
    BN: ['ache', 'aache', 'ami', 'tumi', 'bhalo', 'darun', 'fatafati',
         'pagol', 'aar', 'kemon', 'bolo', 'korchi'],
    OD: ['achhi', 'achi', 'bhala', 'mun', 'mu', 'pain', 'hela',
         'kemiti', 'kana', 'kinichhi'],
  },
  'chinna': {
    TA: ['romba', 'rombha', 'illa', 'illai', 'macha', 'nalla', 'enna',
         'iruku', 'da', 'sollu', 'konjam', 'seri'],
    TE: ['ante', 'andi', 'bagundi', 'chala', 'ledu', 'kaadu', 'undi',
         'ra', 'bava', 'nenu'],
  },
  'paisa': {
    HI: ['hai', 'hain', 'bahut', 'bhot', 'nahi', 'wala', 'zyada', 'kya',
         'wasool', 'yaar', 'lagta'],
    GU: ['chhe', 'che', 'chho', 'saru', 'maza', 'badhu', 'nathi', 'kem'],
    MR: ['ahe', 'aahe', 'khup', 'chaan', 'ka', 'mhanje', 'zalay',
         'tula', 'mala'],
  },
  'paise': {
    HI: ['hai', 'hain', 'bahut', 'bhot', 'nahi', 'wala', 'zyada', 'wasool', 'kya'],
    GU: ['chhe', 'che', 'chho', 'saru', 'maza', 'badhu', 'nathi', 'kem'],
    MR: ['ahe', 'aahe', 'khup', 'chaan', 'mhanje', 'zalay', 'ka'],
  },
  // ═══ GROUP B: CROSS-DRAVIDIAN SHARED TOKENS ═══
  'nalla': {
    TA: ['romba', 'rombha', 'illa', 'illai', 'macha', 'enna', 'konjam',
         'iruku', 'da', 'sollu', 'appuram', 'seri', 'poda'],
    ML: ['anu', 'aanu', 'alle', 'undo', 'ille', 'njan', 'njaanu',
         'kollam', 'adipoli', 'mone', 'mole', 'machaan', 'pakshe', 'sheri'],
  },
  'illa': {
    TA: ['romba', 'rombha', 'macha', 'nalla', 'enna', 'konjam',
         'iruku', 'da', 'sollu', 'appuram', 'seri', 'poda'],
    KN: ['ide', 'idhe', 'ede', 'beku', 'beda', 'thumba', 'tumba',
         'bombat', 'olle', 'namma', 'aa', 'ivattu', 'chennagide'],
  },
  'avan': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'iruku', 'da', 'konjam', 'sollu'],
    ML: ['anu', 'aanu', 'alle', 'undo', 'ille', 'njan',
         'kollam', 'adipoli', 'mone', 'pakshe'],
    KN: ['ide', 'idhe', 'ede', 'illa', 'beku', 'thumba',
         'bombat', 'olle', 'namma', 'chennagide'],
  },
  'aval': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'iruku', 'da', 'konjam', 'sollu'],
    ML: ['anu', 'aanu', 'alle', 'undo', 'ille', 'njan',
         'kollam', 'adipoli', 'mone', 'pakshe'],
    KN: ['ide', 'idhe', 'ede', 'illa', 'beku', 'thumba',
         'bombat', 'olle', 'namma', 'chennagide'],
  },
  'anna': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'iruku', 'da', 'konjam', 'sollu', 'seri'],
    TE: ['ante', 'andi', 'bagundi', 'chala', 'ledu', 'kaadu',
         'undi', 'ra', 'bava', 'nenu'],
  },
  'akka': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'iruku', 'da', 'konjam', 'sollu'],
    TE: ['ante', 'andi', 'bagundi', 'chala', 'ledu', 'kaadu',
         'undi', 'ra', 'bava'],
    KN: ['ide', 'idhe', 'ede', 'illa', 'beku', 'thumba',
         'bombat', 'olle', 'namma', 'aa'],
  },
  'macha': {
    TA: ['romba', 'rombha', 'illa', 'illai', 'nalla', 'enna', 'konjam',
         'iruku', 'da', 'sollu', 'appuram', 'seri'],
    ML: ['anu', 'aanu', 'alle', 'undo', 'ille', 'njan',
         'kollam', 'adipoli', 'mone', 'mole', 'pakshe', 'sheri'],
  },
  'machaan': {
    ML: ['anu', 'aanu', 'alle', 'undo', 'ille', 'njan', 'njaanu',
         'kollam', 'adipoli', 'mone', 'mole', 'pakshe'],
    TA: ['romba', 'rombha', 'illa', 'nalla', 'enna', 'konjam',
         'iruku', 'da', 'sollu', 'seri'],
  },
  'koncham': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'iruku', 'da', 'sollu', 'appuram'],
    TE: ['ante', 'andi', 'bagundi', 'chala', 'ledu', 'kaadu',
         'undi', 'ra', 'bava', 'nenu'],
  },
  'konjam': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'iruku', 'da', 'sollu', 'seri', 'appuram'],
    TE: ['ante', 'andi', 'bagundi', 'chala', 'ledu', 'kaadu',
         'undi', 'ra', 'bava'],
  },
  'ri': {
    TE: ['ante', 'andi', 'bagundi', 'baagundi', 'chala', 'ledu',
         'kaadu', 'undi', 'bava', 'nenu', 'ekkada'],
    KN: ['ide', 'idhe', 'ede', 'illa', 'beku', 'thumba',
         'tumba', 'bombat', 'olle', 'namma', 'aa'],
  },
  'amma': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'konjam', 'iruku', 'da', 'sollu'],
    TE: ['ante', 'andi', 'bagundi', 'chala', 'ledu', 'kaadu', 'undi'],
    ML: ['anu', 'aanu', 'alle', 'undo', 'ille', 'njan',
         'kollam', 'adipoli', 'mone'],
    KN: ['ide', 'idhe', 'ede', 'illa', 'beku', 'thumba',
         'bombat', 'olle', 'namma'],
  },
  // ═══ GROUP C: GRAMMATICAL PARTICLE SHARED TOKENS ═══
  're': {
    BN: ['ache', 'aache', 'ami', 'tumi', 'bhalo', 'khub', 'darun',
         'fatafati', 'aar', 'kemon', 'bolo', 'korchi', 'pagol'],
    MR: ['ahe', 'aahe', 'khup', 'chaan', 'ka', 'mhanje', 'zalay',
         'tula', 'mala', 'aplya', 'tyamule', 'kuthe'],
  },
  'la': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'konjam', 'iruku', 'da', 'sollu', 'seri'],
    MR: ['ahe', 'aahe', 'khup', 'chaan', 'ka', 'mhanje', 'zalay',
         'tula', 'mala', 'aplya', 'tyamule'],
  },
  'ku': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'konjam', 'iruku', 'da', 'sollu'],
    ML: ['anu', 'aanu', 'alle', 'undo', 'ille', 'njan',
         'kollam', 'adipoli', 'mone', 'pakshe'],
    OD: ['achhi', 'achi', 'bhala', 'mun', 'mu', 'pain',
         'hela', 'kemiti', 'kana', 'kinichhi'],
  },
  'main': {
    HI: ['hai', 'hain', 'nahi', 'kya', 'bahut', 'bhot', 'yaar', 'bhai',
         'acha', 'wala', 'zyada', 'lagta', 'lekin', 'sirf'],
    PA: ['hanji', 'wich', 'vich', 'oye', 'tussi', 'tusi', 'vadiya',
         'paji', 'naal', 'kidda', 'assi', 'lagda'],
  },
  'mai': {
    HI: ['hai', 'hain', 'nahi', 'kya', 'bahut', 'yaar', 'bhai',
         'acha', 'wala', 'zyada', 'lagta'],
    PA: ['hanji', 'wich', 'vich', 'oye', 'tussi', 'vadiya',
         'paji', 'naal', 'kidda'],
  },
  'ho': {
    HI: ['kya', 'nahi', 'bhai', 'yaar', 'bahut', 'acha', 'wala',
         'lagta', 'tha', 'mein', 'zyada'],
    MR: ['ahe', 'aahe', 'khup', 'chaan', 'ka', 'mhanje', 'zalay',
         'kuthe', 'aplya', 'tyamule'],
  },
  'ek': {
    HI: ['hai', 'nahi', 'bhai', 'bahut', 'yaar', 'kya', 'zyada', 'wala', 'lagta'],
    MR: ['ahe', 'aahe', 'khup', 'chaan', 'ka', 'mhanje', 'zalay', 'kuthe'],
    GU: ['chhe', 'che', 'chho', 'saru', 'maza', 'badhu', 'nathi', 'kem', 'aavjo'],
  },
  'kya': {
    HI: ['hai', 'hain', 'nahi', 'bhai', 'yaar', 'bahut', 'acha', 'wala',
         'lagta', 'zyada', 'lekin'],
    GU: ['chhe', 'che', 'chho', 'saru', 'maza', 'badhu', 'nathi', 'kem',
         'aavjo', 'su'],
  },
  'dada': {
    BN: ['ache', 'aache', 'ami', 'tumi', 'bhalo', 'khub', 'darun',
         'fatafati', 'aar', 'kemon', 'pagol', 'korchi'],
    OD: ['achhi', 'achi', 'bhala', 'mun', 'mu', 'pain', 'hela',
         'kemiti', 'kana', 'kinichhi'],
    HI: ['hai', 'hain', 'nahi', 'bahut', 'yaar', 'bhai', 'acha', 'kya', 'wala'],
  },
  'toh': {
    BN: ['ache', 'aache', 'ami', 'tumi', 'bhalo', 'khub', 'darun',
         'aar', 'bolo', 'kemon', 'fatafati', 'pagol'],
    PA: ['hanji', 'wich', 'vich', 'oye', 'tussi', 'vadiya', 'paji',
         'naal', 'kidda', 'assi', 'lagda'],
  },
  'se': {
    HI: ['hai', 'nahi', 'kya', 'bhai', 'bahut', 'yaar', 'acha',
         'mein', 'wala', 'zyada', 'lagta'],
    BN: ['ache', 'aache', 'ami', 'tumi', 'bhalo', 'khub', 'darun',
         'aar', 'kemon', 'fatafati'],
  },
  'achhi': {
    HI: ['bahut', 'bhot', 'kya', 'nahi', 'yaar', 'bhai', 'quality',
         'zyada', 'wala', 'lagta', 'hai', 'hain'],
    OD: ['bhala', 'mun', 'mu', 'pain', 'hela', 'kemiti', 'kana',
         'kinichhi', 'bahuta', 'daam'],
    BN: ['ami', 'tumi', 'bhalo', 'khub', 'darun', 'aar',
         'kemon', 'fatafati', 'pagol', 'korchi'],
  },
  'ache': {
    BN: ['ami', 'tumi', 'bhalo', 'khub', 'darun', 'fatafati', 'aar',
         'kemon', 'pagol', 'bolo', 'korchi', 'jacchi'],
    HI: ['bahut', 'bhot', 'kya', 'nahi', 'yaar', 'bhai', 'zyada',
         'wala', 'lagta', 'sahi', 'hai', 'hain'],
  },
  'naa': {
    GU: ['chhe', 'che', 'chho', 'saru', 'maza', 'badhu', 'nathi',
         'kem', 'aavjo', 'su', 'badhu'],
    HI: ['hai', 'nahi', 'kya', 'bhai', 'bahut', 'yaar', 'acha',
         'lagta', 'wala', 'zyada'],
    PA: ['hanji', 'wich', 'vich', 'tussi', 'oye', 'vadiya', 'paji', 'naal'],
  },
  'pa': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'konjam', 'iruku', 'da', 'sollu', 'seri'],
    PA: ['hanji', 'wich', 'vich', 'oye', 'tussi', 'vadiya',
         'naal', 'kidda', 'assi'],
  },
  'kharap': {
    BN: ['ache', 'aache', 'ami', 'tumi', 'bhalo', 'khub', 'darun',
         'fatafati', 'aar', 'kemon', 'pagol'],
    OD: ['achhi', 'achi', 'bhala', 'mun', 'mu', 'pain', 'hela',
         'kemiti', 'kana', 'kinichhi'],
  },
  'eppo': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'konjam', 'iruku', 'da', 'sollu'],
    ML: ['anu', 'aanu', 'alle', 'undo', 'ille', 'njan',
         'kollam', 'adipoli', 'mone', 'pakshe'],
  },
  'pakka': {
    TA: ['romba', 'rombha', 'illa', 'macha', 'nalla', 'enna',
         'konjam', 'iruku', 'da', 'sollu'],
    TE: ['ante', 'andi', 'bagundi', 'chala', 'ledu', 'kaadu',
         'undi', 'ra', 'bava'],
    KN: ['ide', 'idhe', 'ede', 'illa', 'beku', 'thumba',
         'bombat', 'olle', 'namma', 'aa'],
    HI: ['hai', 'hain', 'nahi', 'bhai', 'bahut', 'yaar', 'acha', 'wala', 'zyada'],
  },
};
